import { architectureNodeSchema } from "@/lib/content-schema";

const rawNodes = [
  ["sources", "Job sources", "source", "Approved APIs, ATS feeds, company career pages, and partners enter here.", ["Source responses"], ["Raw job records"], "Per-source credentials stay server-side.", "Source connector", "Phase 4", "A failing source is isolated and its health is reported.", "Mobile never connects directly to sources."],
  ["ingestion", "Ingestion workers", "platform", "Scheduled workers fetch, validate, and queue job records.", ["Raw job records", "Schedules"], ["Queued records", "Source health"], "Workers use least-privilege service identities.", "Ingestion service", "Phase 4", "Retries are bounded and poison jobs move to review.", "Shared backend capability."],
  ["normalize", "Normalization", "intelligence", "Turns source-specific fields into a consistent internal shape.", ["Queued records"], ["Normalized jobs"], "Untrusted content is sanitized before downstream use.", "Job intelligence", "Phase 4", "Invalid records are quarantined with a reason.", "Creates one stable contract for all clients."],
  ["dedupe", "Deduplication", "intelligence", "Finds repeated roles across sources without hiding meaningful differences.", ["Normalized jobs"], ["Canonical candidates"], "Matching operates on limited job data only.", "Job intelligence", "Phase 4", "Uncertain pairs remain separate and are flagged.", "Prevents duplicate mobile alerts."],
  ["canonical", "Canonical jobs", "platform", "Stores the product's reliable representation of each opportunity.", ["Canonical candidates"], ["Versioned jobs"], "RLS and service boundaries restrict user access.", "PostgreSQL", "Phase 4", "Previous versions remain traceable.", "Mobile reads versioned API responses."],
  ["extract", "Requirement extraction", "intelligence", "Structures responsibilities, skills, constraints, and application instructions.", ["Canonical jobs"], ["Requirement sets"], "Prompts exclude unnecessary user data.", "AI job intelligence", "Phase 5", "Low-confidence extraction is marked, not guessed.", "Clients receive explanations, not raw provider output."],
  ["match", "Career matching", "intelligence", "Compares requirements with verified profile evidence across separate dimensions.", ["Requirement sets", "Career profile"], ["Verdicts", "Gaps", "Blockers"], "User facts remain tenant-scoped.", "Matching engine", "Phase 5", "Deterministic blockers survive model outages.", "Same verdict contract powers web and mobile."],
  ["analysis", "Deep AI analysis", "intelligence", "Explains transferable strengths, learnable gaps, and application value.", ["Verdicts", "Evidence"], ["Grounded explanation"], "Provider calls are audited and redact excess context.", "AI orchestration", "Phase 5", "The system degrades to basic deterministic analysis.", "Analysis is prepared centrally."],
  ["pack", "Application Pack", "experience", "Assembles review-ready documents only after evidence and entitlement checks pass.", ["Analysis", "Verified facts", "Style settings"], ["Cover letter", "Resume", "Guidance"], "Claim verification removes unsupported statements.", "Document service", "Phase 6", "A failed component does not publish a partial pack silently.", "Documents are reviewable on mobile."],
  ["alerts", "Alerts", "experience", "Routes worthwhile opportunities and reminders through user-approved channels.", ["Verdicts", "Preferences"], ["Email", "Browser", "Future push"], "Consent and channel preferences are enforced.", "Notification service", "Phase 7", "Rate limits and digests prevent alert storms.", "Future push uses the same event model."],
  ["clients", "Web and mobile clients", "experience", "Present the same career system through context-appropriate interfaces.", ["Versioned API"], ["User actions"], "No privileged business rule depends on a client.", "Product clients", "Phase 1 / Future mobile", "Unsupported clients receive clear upgrade guidance.", "React Native remains a future phase."],
  ["control", "Admin control plane", "control", "Manages sources, prompts, models, plans, flags, versions, and audit review.", ["Operational state"], ["Approved configuration"], "Separate admin authentication and immutable audit events.", "Operations", "Cross-phase", "Dangerous changes require confirmation and rollback paths.", "Platform flags can disable mobile features safely."],
] as const;

export const architectureNodes = architectureNodeSchema.array().parse(
  rawNodes.map(([id, label, layer, purpose, inputs, outputs, security, ownership, phase, failure, mobile]) => ({
    id, label, layer, purpose, inputs, outputs, security, ownership, phase, failure, mobile,
  })),
);
