import { roadmapPhaseSchema } from "@/lib/content-schema";

const rawRoadmap = [
  {
    id: "phase-0",
    number: "00",
    title: "Foundation and architecture",
    status: "Planned",
    purpose: "Create the secure, mobile-ready base every later capability depends on.",
    deliverables: ["Monorepo and design system", "Supabase, API, and worker foundations", "Plans and entitlements", "RLS, security, and documentation"],
    dependencies: [],
    gates: ["Threat model reviewed", "RLS policies tested", "Mobile-facing contracts versioned"],
    risks: ["Premature product logic in clients", "Unclear data ownership"],
    decisions: ["Confirm production hosting and repository strategy"],
  },
  {
    id: "phase-1",
    number: "01",
    title: "Authentication and SaaS experience",
    status: "Planned",
    purpose: "Give customers and operators a safe, coherent entry into Hanaply.",
    deliverables: ["Registration and login", "Verification and password reset", "Customer dashboard", "Admin authentication", "Account and session controls"],
    dependencies: ["Phase 0"],
    gates: ["Account recovery tested", "Admin boundary independently reviewed"],
    risks: ["Session handling drift across future clients"],
    decisions: ["Define support policy for account recovery"],
  },
  {
    id: "phase-2",
    number: "02",
    title: "Plans and manual payments",
    status: "Planned",
    purpose: "Validate paid access with a transparent Philippines-first activation flow.",
    deliverables: ["Activation Center", "GCash, Maya, and bank transfer instructions", "Proof upload and admin review", "Subscription activation", "Entitlement enforcement"],
    dependencies: ["Phase 1"],
    gates: ["Payment evidence access is restricted", "Every activation is auditable"],
    risks: ["Manual review delays", "Payment proof contains sensitive information"],
    decisions: ["Set review hours and refund policy"],
  },
  {
    id: "phase-3",
    number: "03",
    title: "Career Intelligence Profile",
    status: "Planned",
    purpose: "Represent a person through verified career evidence, not a keyword list.",
    deliverables: ["Main and sub-careers", "Skills, experience, and projects", "Resume and portfolio", "Verified facts and preferences", "Career taxonomy"],
    dependencies: ["Phase 1"],
    gates: ["Fact provenance is visible", "Deletion and export are tested"],
    risks: ["Profiles become broad but shallow", "Taxonomy creates false precision"],
    decisions: ["Approve initial career taxonomy"],
  },
  {
    id: "phase-4",
    number: "04",
    title: "Job ingestion",
    status: "Planned",
    purpose: "Build a dependable stream of fresh, lawful, normalized opportunities.",
    deliverables: ["Approved APIs and ATS feeds", "Company career sources", "Normalization and deduplication", "Freshness and source health"],
    dependencies: ["Phase 0", "Phase 3"],
    gates: ["Source terms reviewed", "Duplicate rate measured", "Broken sources fail safely"],
    risks: ["Source instability", "Stale or duplicated listings"],
    decisions: ["Approve first source set"],
  },
  {
    id: "phase-5",
    number: "05",
    title: "AI job intelligence",
    status: "Planned",
    purpose: "Explain whether an opportunity makes sense for this person and why.",
    deliverables: ["Requirement extraction", "Multi-dimensional matching", "Verdicts and hard blockers", "Transferable and learnable gaps", "Explainable recommendations"],
    dependencies: ["Phase 3", "Phase 4"],
    gates: ["Explanations cite source evidence", "High-risk blockers have deterministic checks"],
    risks: ["Confident but unsupported recommendations", "Model inconsistency"],
    decisions: ["Set verdict thresholds and escalation rules"],
  },
  {
    id: "phase-6",
    number: "06",
    title: "Application Packs",
    status: "Planned",
    purpose: "Turn worthy opportunities into truthful, review-ready application material.",
    deliverables: ["Truth Gate", "Cover letters and tailored resumes", "Variations and templates", "Editing, PDF, and DOCX", "Usage limits"],
    dependencies: ["Phase 3", "Phase 5"],
    gates: ["Every claim is grounded", "Documents remain editable", "Exports pass ATS checks"],
    risks: ["Fabricated or overstated claims", "Template formatting regressions"],
    decisions: ["Approve initial style library"],
  },
  {
    id: "phase-7",
    number: "07",
    title: "Alerts and tracking",
    status: "Planned",
    purpose: "Help users act at the right moment and follow through with care.",
    deliverables: ["Instant alerts and daily digest", "Browser notifications", "Saved jobs", "Application tracker", "Follow-ups and reminders"],
    dependencies: ["Phase 4", "Phase 5"],
    gates: ["Users control every channel", "Duplicates never create alert storms"],
    risks: ["Notification fatigue", "Timezone errors"],
    decisions: ["Approve Manila-first delivery windows"],
  },
  {
    id: "phase-8",
    number: "08",
    title: "Premium design and animation",
    status: "Planned",
    purpose: "Refine the product into a fast, accessible, high-trust experience.",
    deliverables: ["Radar storytelling", "Dashboard transitions", "Accessibility", "Performance", "Responsive refinement"],
    dependencies: ["Phases 1–7"],
    gates: ["WCAG 2.2 AA review", "Reduced motion parity", "Performance budgets met"],
    risks: ["Motion obscures meaning", "Visual polish slows core workflows"],
    decisions: ["Approve production design direction"],
  },
  {
    id: "phase-9",
    number: "09",
    title: "AI Career Coach",
    status: "Planned",
    purpose: "Turn application activity into practical, evidence-based career guidance.",
    deliverables: ["Weekly strategy", "Interview preparation", "Skill-gap plans", "Recruiter messages", "Career-transition guidance", "Application-performance analysis"],
    dependencies: ["Phases 5–7"],
    gates: ["Advice limitations are explicit", "User can inspect supporting evidence"],
    risks: ["Over-prescriptive advice", "Sensitive inference"],
    decisions: ["Define coaching safety boundaries"],
  },
  {
    id: "phase-10",
    number: "10",
    title: "Mobile readiness completion",
    status: "Planned",
    purpose: "Stabilize shared contracts and operational controls before mobile clients ship.",
    deliverables: ["Stable mobile API", "Devices and push tokens", "Deep links", "Version controls", "Platform flags"],
    dependencies: ["Phases 0–9"],
    gates: ["Backward compatibility tested", "Kill switches and maintenance mode verified"],
    risks: ["Client version fragmentation"],
    decisions: ["Set supported-version policy"],
  },
  {
    id: "future-mobile",
    number: "M",
    title: "Future mobile phase",
    status: "Planned",
    purpose: "Bring the same trusted career system to focused mobile moments.",
    deliverables: ["React Native iOS and Android", "Shared authentication and entitlements", "Job Radar and Application Packs", "Tracking and push notifications"],
    dependencies: ["Phase 10"],
    gates: ["Store readiness review", "Document review is usable on small screens"],
    risks: ["Duplicated business rules", "Notification overload"],
    decisions: ["Choose initial platform launch order"],
  },
] as const;

export const roadmap = roadmapPhaseSchema.array().parse(rawRoadmap);
